version: '3.5'
services:
    instace-01.app:
        build:
            context: .docker/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        container_name: instace-01
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '91:80'
            - '5177:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

    instace-02.app:
        build:
            context: .docker/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        container_name: instace-02
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '92:80'
            - '5178:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

    zookeeper:
        image: confluentinc/cp-zookeeper:7.2.1
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        networks:
            - sail
    kafka1:
        image: confluentinc/cp-kafka:7.2.1
        container_name: kafka1
        ports:
            - "8097:8097"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8097,INTERNAL://kafka1:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
        networks:
            - sail
    kafka2:
        image: confluentinc/cp-kafka:7.2.1
        container_name: kafka2
        ports:
            - "8098:8098"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8098,INTERNAL://kafka2:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
        networks:
            - sail
    kafka3:
        image: confluentinc/cp-kafka:7.2.1
        container_name: kafka3
        ports:
            - "8099:8099"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8099,INTERNAL://kafka3:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
        networks:
            - sail
networks:
    sail:
        driver: bridge
